AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Handson VPC stack...

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: handson-vpc

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a

  RouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref RouteTable1

  HandsonSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Handson SG
      VpcId: !Ref VPC
      SecurityGroupIngress: []

Outputs:
  VpcId:
    Value: !Ref VPC
  SubnetId:
    Value: !Ref Subnet1
  SecurityGroupId:
    Value: !GetAtt HandsonSecurityGroup.GroupId
